language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4.1"
  - "0.12"
  - "0.10"
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
